<h3> Importing the Libraries Needed for Mathematical Statistics </h3>

In [2]:
import numpy as np
import pandas as pd
import matplotlib as mplt

<h3> Working with SIngle and Multidimensional Arrays </h3>

In [6]:
ar1 = np.array([1,2,3,4,5,6,7,8,9,10,])
ar2 = np.array([[10,11,12],[20,21,22],[30,31,32]])
print("Single Dimensional Array: ", ar1)
print("Multi Dimensional ", ar2.shape, " Array :\n", ar2)

#Create an array of desired Dimensions using Zeros/ initialize an array
ar3 = np.zeros(ar1.shape)
ar4 = np.zeros(ar2.shape)
print("Single Dimensional Array: ", ar3);
print("Multi Dimensional Array: \n", ar4);

#Create a vector using Numpy linspace
ar5 = np.linspace(0, 100, 10) # Starting Point, Gap, Stopping Point
print("Array using linear spacing: ", ar5)

#Any List/ Vector or Python array needs to be converted into a numpy array before working on it
customArray = [1,4,3,6,2,5]
ar6 = np.asarray(customArray)

#Creating a 2D array from a Flat array
customArray2 = [3,2,5,1,6,0,9,8]
ar7 = np.asarray(customArray2)
ar7.reshape(2,2,2)

ar8 = np.zeros((2,3,3))
print("Flattened array Length:", ar8.ravel().shape)


Single Dimensional Array:  [ 1  2  3  4  5  6  7  8  9 10]
Multi Dimensional  (3, 3)  Array :
 [[10 11 12]
 [20 21 22]
 [30 31 32]]
Single Dimensional Array:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Multi Dimensional Array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array using linear spacing:  [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
Flattened array Length: (18,)


In [10]:
# Indexing of Numpy Arrays

'''arange is for whole intergers, if you need to use
Floating Point numbers then best to use linspace'''
ar1 = np.arange(2,10) 

print(ar1[4]) #Should print 6

#Slicing the array
ar2 = np.linspace(2,16,2)
print("Initial Array:", ar2)
print("Sliced Array:", ar2[6:10])

#Extracting specific Rows and Columns Using Slicing
ar3 = np.array([[2,4,2], [0,0,0], [11,21,31]])
print("Extracting the first 2 rows and last 2 columns:\n", ar3[0:2, 1:3])


6
Initial Array: [ 2. 16.]
Sliced Array: []
Extracting the first 2 rows and last 2 columns:
 [[4 2]
 [0 0]]


In [11]:
# Numpy array Attributes
ar0 = np.array([
        [[0,0],[1,3]],
        [[2,0],[5,5]]])
print ("Shape:", ar0.shape) # Should return shape 2,2,2
print ("Dimensions:", ar0.ndim) # Should return Dimension 3


Shape: (2, 2, 2)
Dimensions: 3


<h3> Quick Ramp Up on Pandas </h3>
<p>Pandas build on top of Numpy by providing 3 types of Data types:</p>
    <ol>
        <ul>1D -> Series</ul>
        <ul>2D -> Dataframes</ul>
        <ul>3D -> Panels</ul>
    </ol>


In [17]:
#Series in Pandas

# Creating a new Series
s1= pd.Series()
print("\nNew Series created", s1)

#Creating a Series from numpy array
np1 = np.arange(1,20,5)
s2 = pd.Series(np1)
print("\nSeries from Numpy array:\n", s2)

# Series from a Python Dictionary
dict = {'sub1': 'Probability', 'sub2': 'Artificial Intelligence', 'sub3' : 'Linear Algebra'}
print("\nSeries from a dictionary\n", pd.Series(dict))



New Series created Series([], dtype: object)

Series from Numpy array:
 0     1
1     6
2    11
3    16
dtype: int32

Series from a dictionary
 sub1                Probability
sub2    Artificial Intelligence
sub3             Linear Algebra
dtype: object


In [6]:
#Data Farmes in Pandas
data = [{'sub1': 'Probability', 'sub2': 'Linear Algebra'},{'sub1': 'Chemistry', 'sub2': 'Artificial Intelligence', 'sub3': 'Vector Aritmetics'}]
pdDataframe = pd.DataFrame(data);
print(pdDataframe)
df2 = pd.DataFrame(data, index = ['Course 1', 'Course 2']);
print (df2)

          sub1                     sub2               sub3
0  Probability           Linear Algebra                NaN
1    Chemistry  Artificial Intelligence  Vector Aritmetics
                 sub1                     sub2               sub3
Course 1  Probability           Linear Algebra                NaN
Course 2    Chemistry  Artificial Intelligence  Vector Aritmetics


: 